name: Build and Deploy Azure Static Web App

on:
  push:
    branches:
      - prod
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - prod
      - dev

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Add Issues from Comments
        uses: "alstr/todo-to-issue-action@v4"
        with:
          AUTO_ASSIGN: true
          CLOSE_ISSUES: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_PEBBLE_0D62EB803 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: "api"
          output_location: "dist"
          skip_app_build: true
        env:
          # API variables
          FORM_WORKSHOP_BOOKING: ${{ secrets.FORM_WORKSHOP_BOOKING }}
          FORM_CONTACT: ${{secrets.FORM_CONTACT}}
          FORM_WORKSHOP_PREP: ${{secrets.FORM_WORKSHOP_PREP}}
          FORM_WORKSHOP_FEEDBACK: ${{secrets.FORM_WORKSHOP_FEEDBACK}}
          # Site Variables
          NOTIST_FEED: ${{ secrets.NOTIST_FEED }}
          API_URL: ${{ secrets.API_URL }}
          SITE_URL: ${{ secrets.SITE_URL }}
          PAGE_WORKSHOP_FEEDBACK: ${{secrets.PAGE_WORKSHOP_FEEDBACK}}
          PAGE_WORKSHOP_PREP: ${{secrets.PAGE_WORKSHOP_PREP}}

      - name: Rebuild and Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_PEBBLE_0D62EB803 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: "api"
          output_location: "dist"
          skip_app_build: true
        env:
          # API variables
          FORM_WORKSHOP_BOOKING: ${{ secrets.FORM_WORKSHOP_BOOKING }}
          FORM_CONTACT: ${{secrets.FORM_CONTACT}}
          FORM_WORKSHOP_PREP: ${{secrets.FORM_WORKSHOP_PREP}}
          FORM_WORKSHOP_FEEDBACK: ${{secrets.FORM_WORKSHOP_FEEDBACK}}
          # Site Variables
          NOTIST_FEED: ${{ secrets.NOTIST_FEED }}
          API_URL: ${{ secrets.API_URL }}
          SITE_URL: ${{ secrets.SITE_URL }}
          PAGE_WORKSHOP_FEEDBACK: ${{secrets.PAGE_WORKSHOP_FEEDBACK}}
          PAGE_WORKSHOP_PREP: ${{secrets.PAGE_WORKSHOP_PREP}}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_PEBBLE_0D62EB803 }}
          action: "close"
